# Generated by Django 4.1.3 on 2022-11-07 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0002_alter_recipe_options_recipe_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="favorite",
            field=models.ManyToManyField(
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Избранные рецепты",
            ),
        ),
    ]
